Repository boostcampwm2023/web16-B1G1, pull requests merged in 2023-11, with the labels that each got.

#2 :tada: Initialize NestJS project
  BE/.eslintrc.js
  BE/.prettierrc
  BE/.yarn/releases/yarn-4.0.1.cjs
  BE/.yarnrc.yml
  BE/README.md
  BE/nest-cli.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/main.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/tsconfig.build.json
  BE/tsconfig.json
  BE/yarn.lock
Labels: ⚙ Setting

#73 [FE] 라우터 세팅
  .pnp.cjs
  .yarn/cache/@remix-run-router-npm-1.11.0-528ee8c1c1-046b382e14.zip
  .yarn/cache/@types-history-npm-4.7.11-fe05d7b2e1-3facf37c24.zip
  .yarn/cache/@types-react-router-dom-npm-5.3.3-9f687b5b3a-a9231a16af.zip
  .yarn/cache/@types-react-router-npm-5.1.20-620ccce99a-1f7eee6198.zip
  .yarn/cache/react-router-dom-npm-6.18.0-72373ba9f8-9c2893f6b9.zip
  .yarn/cache/react-router-npm-6.18.0-4754c0f86e-185d240cb8.zip
  .yarn/install-state.gz
  package.json
  packages/client/package.json
  packages/client/src/App.css
  packages/client/src/App.tsx
  packages/client/src/assets/react.svg
  packages/client/src/index.css
  packages/client/src/main.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Home/styled.ts
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/pages/Landing/styled.ts
  yarn.lock
Labels: ✨ Feature, FE

#74 [FE] 디렉토리 구조 초기화
  .gitignore
  packages/client/src/App.tsx
  packages/client/src/apis/.gitkeep
  packages/client/src/components/common/.gitkeep
  packages/client/src/components/feature/.gitkeep
  packages/client/src/constants/.gitkeep
  packages/client/src/hooks/.gitkeep
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/store/.gitkeep
  packages/client/src/styles/.gitkeep
  packages/client/src/types/.gitkeep
  packages/client/src/utils/.gitkeep
Labels: ⚙ Setting, FE

#76 [BE] [13-01] Dockerfile 생성 및 클라우드 환경에 배포
  Dockerfile
Labels: 🚀 Deploy, BE

#80 [FE] [01-02] 우주 배경 생성
  .pnp.cjs
  .yarn/cache/@types-stats.js-npm-0.17.3-72645350c6-ccccc992c6.zip
  .yarn/cache/@types-three-npm-0.158.2-e8e6f6f7b1-bd7f85c719.zip
  .yarn/cache/globrex-npm-0.1.2-ddda94f2d0-a54c029520.zip
  .yarn/cache/meshoptimizer-npm-0.18.1-ce62c2344d-8a825c58b2.zip
  .yarn/cache/tsconfck-npm-2.1.2-ddaf839ffe-6efc9cbbcc.zip
  .yarn/cache/vite-tsconfig-paths-npm-4.2.1-85e1292184-982fb89b9e.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/components/feature/.gitkeep
  packages/client/src/components/feature/BackgroundStars/index.tsx
  packages/client/src/components/feature/Screen/index.tsx
  packages/client/src/components/feature/Star/index.tsx
  packages/client/src/constants/.gitkeep
  packages/client/src/constants/backgroundStars.ts
  packages/client/src/constants/space.ts
  packages/client/src/pages/Home/index.tsx
  packages/client/src/utils/.gitkeep
  packages/client/src/utils/random.ts
  packages/client/tsconfig.json
  packages/client/vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css", FE

#81 [FE] [06-03] 은하 생성 🌌
  .pnp.cjs
  .yarn/cache/@floating-ui-core-npm-1.5.0-3cdde0a88b-bca811cefd.zip
  .yarn/cache/@floating-ui-dom-npm-1.5.3-ac36b589ae-e5f30b911f.zip
  .yarn/cache/@floating-ui-react-dom-npm-2.0.4-e347c2e4b4-5d597a7939.zip
  .yarn/cache/@floating-ui-utils-npm-0.1.6-ae508f7272-0a089db0e0.zip
  .yarn/cache/@radix-ui-primitive-npm-1.0.1-cbcafe0446-9122164555.zip
  .yarn/cache/@radix-ui-react-arrow-npm-1.0.3-d57b8cf08f-c931f6d7e0.zip
  .yarn/cache/@radix-ui-react-compose-refs-npm-1.0.1-02d1046f7d-be06f8dab3.zip
  .yarn/cache/@radix-ui-react-context-npm-1.0.1-c6d8414c9a-3de5761b32.zip
  .yarn/cache/@radix-ui-react-dismissable-layer-npm-1.0.5-fbc4b71169-7e4308867a.zip
  .yarn/cache/@radix-ui-react-id-npm-1.0.1-d2f01e7fd5-e2859ca58b.zip
  .yarn/cache/@radix-ui-react-popper-npm-1.1.3-d7804f4c70-a38c374ec6.zip
  .yarn/cache/@radix-ui-react-portal-npm-1.0.4-e4c93f6e90-fed32f8148.zip
  .yarn/cache/@radix-ui-react-presence-npm-1.0.1-2057bd46b4-90780618b2.zip
  .yarn/cache/@radix-ui-react-primitive-npm-1.0.3-1983a5adc0-67a66ff889.zip
  .yarn/cache/@radix-ui-react-slot-npm-1.0.2-b9078e9a0b-3af6ea4891.zip
  .yarn/cache/@radix-ui-react-tooltip-npm-1.0.7-c7378e5c03-915524ea9d.zip
  .yarn/cache/@radix-ui-react-use-callback-ref-npm-1.0.1-e521cb00a3-331b432be1.zip
  .yarn/cache/@radix-ui-react-use-controllable-state-npm-1.0.1-cbe6fcf1d7-29b069dbf0.zip
  .yarn/cache/@radix-ui-react-use-escape-keydown-npm-1.0.3-2455d95aa3-3c94c78902.zip
  .yarn/cache/@radix-ui-react-use-layout-effect-npm-1.0.1-fa00f2498d-13cd0c3839.zip
  .yarn/cache/@radix-ui-react-use-rect-npm-1.0.1-ea3f7a385f-94c5ab31df.zip
  .yarn/cache/@radix-ui-react-use-size-npm-1.0.1-97c8358b35-b109a4b378.zip
  .yarn/cache/@radix-ui-react-visually-hidden-npm-1.0.3-16767f48b2-0cbc12c215.zip
  .yarn/cache/@radix-ui-rect-npm-1.0.1-035cf20ddc-4c51596613.zip
  .yarn/cache/@react-three-postprocessing-npm-2.15.11-309b8c1a2e-9529ab2837.zip
  .yarn/cache/@stitches-react-npm-1.2.8-445a1042b8-d9c03cd88a.zip
  .yarn/cache/assign-symbols-npm-1.0.0-fd803ccdf1-29a654b8a6.zip
  .yarn/cache/attr-accept-npm-2.2.2-b9cd0d8eac-f77c073ac9.zip
  .yarn/cache/colord-npm-2.9.3-5c35c27898-9699e95689.zip
  .yarn/cache/dequal-npm-2.0.3-53a630c60e-f98860cdf5.zip
  .yarn/cache/extend-shallow-npm-2.0.1-e6ef52b29c-ee1cb0a18c.zip
  .yarn/cache/extend-shallow-npm-3.0.2-77bbe1bbf5-f39581b8f9.zip
  .yarn/cache/file-selector-npm-0.5.0-c731a8ed22-e29c5e0769.zip
  .yarn/cache/for-in-npm-1.0.2-37e3d7aae5-42bb609d56.zip
  .yarn/cache/get-value-npm-2.0.6-03cd422e0a-f069c13279.zip
  .yarn/cache/is-extendable-npm-0.1.1-322b4649ec-dd5ca3994a.zip
  .yarn/cache/is-extendable-npm-1.0.1-7095ad8b16-1d6678a5be.zip
  .yarn/cache/is-plain-object-npm-2.0.4-da3265d804-f050fdd520.zip
  .yarn/cache/isobject-npm-3.0.1-8145901fd2-03344f5064.zip
  .yarn/cache/leva-npm-0.9.35-da054c7dd9-9555db5e0b.zip
  .yarn/cache/maath-npm-0.6.0-bf6e867013-a9b716841d.zip
  .yarn/cache/merge-value-npm-1.0.0-30d67b896c-1d3c9cae72.zip
  .yarn/cache/mixin-deep-npm-1.3.2-29b528e571-cb39ffb73c.zip
  .yarn/cache/n8ao-npm-1.6.8-e3fcccd5d8-fd71b5387a.zip
  .yarn/cache/postprocessing-npm-6.33.3-3d9d3b5288-d5d28668d6.zip
  .yarn/cache/react-colorful-npm-5.6.1-ba0c706357-48eb73cf71.zip
  .yarn/cache/react-dropzone-npm-12.1.0-56c67f77aa-6afa779d6b.zip
  .yarn/cache/set-value-npm-2.0.1-35da5f8180-4c40573c4f.zip
  .yarn/cache/split-string-npm-3.1.0-df5d83450e-72d7cd6254.zip
  .yarn/cache/v8n-npm-1.5.1-670231b6b7-064f735dc2.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/components/feature/Galaxy/index.tsx
  packages/client/src/components/feature/Screen/index.tsx
  packages/client/src/components/feature/Star/index.tsx
  packages/client/src/constants/camera.ts
  packages/client/src/constants/galaxy.ts
  packages/client/src/constants/star.ts
  yarn.lock
Labels: ✨ Feature, ♻️ Refactor, FE

#82 [BE] [08-06] POST /board 실패하는 테스트 코드 작성(RED), 통과하도록 board 컨트롤러, 서비스 메소드 구현(GREEN)
  .yarn/install-state.gz
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/test/board/board.e2e-spec.ts
Labels: ✨ Feature, ✅ Test, BE

#83 [BE] [06-02] GET /board/:id TDD로 구현 #39
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/test/board/board.e2e-spec.ts
Labels: ✨ Feature, ♻️ Refactor, ✅ Test, BE

#87 [FE] [14-01] Router 사용 방식 변경
  packages/client/index.html
  packages/client/src/App.tsx
  packages/client/src/Router.tsx
  packages/client/src/main.tsx
Labels: ⚡️ Enhancement, FE

#90 [BE] [06-08, 06-13, 06-14, 06-15, 09-03] 게시글 CRUD API 구현
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/test/board/board.e2e-spec.ts
Labels: ✨ Feature, ♻️ Refactor, ✅ Test, BE

#92 [FE] [06-04] 별 클릭시 해당 방향으로 카메라 시점 이동하도록 설정
  .pnp.cjs
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-ac4814e559.zip
  .yarn/cache/zustand-npm-4.4.6-514e0f647e-78ed41a9e9.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/components/feature/Controls/Controls.tsx
  packages/client/src/components/feature/Galaxy/index.tsx
  packages/client/src/components/feature/Screen/index.tsx
  packages/client/src/components/feature/Star/index.tsx
  packages/client/src/constants/galaxy.ts
  packages/client/src/constants/star.ts
  packages/client/src/store/.gitkeep
  packages/client/src/store/useCameraStore.ts
  yarn.lock
Labels: ✨ Feature, FE

#94 [FE] [06-05] 별글 컴포넌트 구현, 간단한 레이블 디자인
  .pnp.cjs
  .yarn/cache/@emotion-babel-plugin-npm-11.11.0-c1dcc4c884-89cbb6ec0e.zip
  .yarn/cache/@emotion-cache-npm-11.11.0-3e6e449071-a23ab5ab2f.zip
  .yarn/cache/@emotion-hash-npm-0.9.1-650576c2b1-cdafe5da63.zip
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.1-794afe6a94-7c2aabdf0c.zip
  .yarn/cache/@emotion-memoize-npm-0.8.1-9b1e35ff15-dffed372fc.zip
  .yarn/cache/@emotion-react-npm-11.11.1-a07d6a6ebd-1aea4d735b.zip
  .yarn/cache/@emotion-serialize-npm-1.1.2-4b856d3761-d243e0e5ab.zip
  .yarn/cache/@emotion-sheet-npm-1.2.2-a918ac483c-69827a1bfa.zip
  .yarn/cache/@emotion-styled-npm-11.11.0-9a95c8527d-a168bd7a8a.zip
  .yarn/cache/@emotion-unitless-npm-0.8.1-bcf0a8f565-a1ed508628.zip
  .yarn/cache/@emotion-use-insertion-effect-with-fallbacks-npm-1.0.1-730758c66c-a15b216794.zip
  .yarn/cache/@emotion-utils-npm-1.2.1-3d04f99348-db43ca8033.zip
  .yarn/cache/@emotion-weak-memoize-npm-0.3.1-bfc18213af-ed514b3cb9.zip
  .yarn/cache/@types-parse-json-npm-4.0.2-f87f65692e-b1b863ac34.zip
  .yarn/cache/babel-plugin-macros-npm-3.1.0-320e781f4e-c6dfb15de9.zip
  .yarn/cache/convert-source-map-npm-1.9.0-e294555f4b-281da55454.zip
  .yarn/cache/cosmiconfig-npm-7.1.0-13a5090bcd-b923ff6af5.zip
  .yarn/cache/find-root-npm-1.1.0-a16a94005f-1abc7f3bf2.zip
  .yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-fe0889169e.zip
  .yarn/cache/source-map-npm-0.5.7-7c3f035429-904e767bb9.zip
  .yarn/cache/stylis-npm-4.2.0-6b07f11c99-a7128ad5a8.zip
  .yarn/cache/yaml-npm-1.10.2-0e780aebdf-5c28b9eb7a.zip
  .yarn/install-state.gz
  package.json
  packages/client/package.json
  packages/client/src/components/feature/PostStars/index.tsx
  packages/client/src/components/feature/Screen/index.tsx
  packages/client/src/components/feature/Star/index.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#99 [FE] [04-09] 페이지 간 이동시 보여줄 화면 제작
  packages/client/src/components/feature/SpaceWarp/index.tsx
  packages/client/src/components/feature/Star/index.tsx
  packages/client/src/constants/spaceWarp.ts
  packages/client/src/pages/Home/index.tsx
Labels: ✨ Feature, FE

#104 [BE] Redis 연결 설정 및 테스트 코드 작성, API 구현
  .pnp.cjs
  .yarn/cache/@ioredis-commands-npm-1.2.0-47541de88b-a5d3c29dd8.zip
  .yarn/cache/cluster-key-slot-npm-1.1.2-0571a28825-d7d39ca28a.zip
  .yarn/cache/ioredis-npm-5.3.2-58471071b1-0dd2b5b800.zip
  .yarn/cache/lodash.defaults-npm-4.2.0-c5dea025ab-d5b77aeb70.zip
  .yarn/cache/lodash.isarguments-npm-3.1.0-9e74d350b8-5e8f95ba10.zip
  .yarn/cache/redis-errors-npm-1.2.0-a81fd9b0f1-5b316736e9.zip
  .yarn/cache/redis-parser-npm-3.0.0-7ebe40abcb-ee16ac4c7b.zip
  .yarn/cache/standard-as-callback-npm-2.1.0-8e47620bd4-012677236e.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/redis.repository.ts
  packages/server/src/board/board.service.ts
  packages/server/src/config/redis.config.ts
  packages/server/src/config/typeorm.config.ts
  packages/server/test/auth/auth.e2e-spec.ts
  yarn.lock
Labels: ✨ Feature, BE

#116 [FE] @emotion/react 패키지 설치
  .pnp.cjs
  .yarn/cache/@types-node-npm-20.9.2-ada70863a8-891a035a5b.zip
  .yarn/install-state.gz
  packages/client/package.json
  yarn.lock
Labels: ⚙ Setting, FE

#117 [FE] 디자인 시스템 적용
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/public/icons/icon-add-24-white.svg
  packages/client/public/icons/icon-arrow-left-32-white.svg
  packages/client/public/icons/icon-arrow-right-17-white.svg
  packages/client/public/icons/icon-arrow-right-32-white.svg
  packages/client/public/icons/icon-back-32-white.svg
  packages/client/public/icons/icon-confirm-22.svg
  packages/client/public/icons/icon-eraser-24-active.svg
  packages/client/public/icons/icon-eraser-24-default.svg
  packages/client/public/icons/icon-naver-16-white.svg
  packages/client/public/icons/icon-pen-24-active.svg
  packages/client/public/icons/icon-pen-24-default.svg
  packages/client/public/icons/icon-photo-32-gray.svg
  packages/client/public/icons/icon-planetedit-24-white.svg
  packages/client/public/icons/icon-search-24-white.svg
  packages/client/public/icons/icon-shuffle-24-gray.svg
  packages/client/public/icons/icon-shuffle-24-white.svg
  packages/client/public/icons/icon-writte-24-white.svg
  packages/client/public/vite.svg
  packages/client/src/shared/ui/colors.ts
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/typos.ts
Labels: 🎨 HTML&CSS, FE

#118 [FE] styles 폴더 생성
  .yarn/install-state.gz
  packages/client/src/shared/ui/styles/colors.ts
  packages/client/src/shared/ui/styles/index.ts
  packages/client/src/shared/ui/styles/typos.ts
  packages/client/src/shared/ui/typos.ts
Labels: ⚙ Setting, FE

#119 [FE] 전역 스타일 정의
  .pnp.cjs
  .yarn/cache/@arcanis-slice-ansi-npm-1.1.1-a69aa37ccc-2f222b121b.zip
  .yarn/cache/@sindresorhus-is-npm-4.6.0-7cad05c55e-33b6fb1d08.zip
  .yarn/cache/@szmarczak-http-timer-npm-4.0.6-6ace00d82d-73946918c0.zip
  .yarn/cache/@types-cacheable-request-npm-6.0.3-770619032a-10816a88e4.zip
  .yarn/cache/@types-emscripten-npm-1.39.10-3b81552c03-c9adde9307.zip
  .yarn/cache/@types-http-cache-semantics-npm-4.0.4-6d4f413ddd-51b72568b4.zip
  .yarn/cache/@types-keyv-npm-3.1.4-a8082ea56b-ff8f54fc49.zip
  .yarn/cache/@types-responselike-npm-1.0.3-de0150f03d-a58ba341cb.zip
  .yarn/cache/@types-semver-npm-7.5.6-9d2637fc95-196dc32db5.zip
  .yarn/cache/@types-treeify-npm-1.0.3-ef5ef3400e-758902638f.zip
  .yarn/cache/@yarnpkg-core-npm-4.0.2-9a073b0439-8406ce7cfe.zip
  .yarn/cache/@yarnpkg-fslib-npm-3.0.1-df63ac76ba-f7dea9bd29.zip
  .yarn/cache/@yarnpkg-libzip-npm-3.0.0-13ff999030-1aa06a1da0.zip
  .yarn/cache/@yarnpkg-parsers-npm-3.0.0-f62f25a57b-cec2c6dd6e.zip
  .yarn/cache/@yarnpkg-sdks-npm-3.1.0-a480fb9a26-cb50660ef3.zip
  .yarn/cache/@yarnpkg-shell-npm-4.0.0-3927f33f2f-040728146c.zip
  .yarn/cache/cacheable-lookup-npm-5.0.4-8f13e8b44b-a6547fb495.zip
  .yarn/cache/cacheable-request-npm-7.0.4-92bf077a92-0834a7d17a.zip
  .yarn/cache/chalk-npm-3.0.0-e813208025-ee650b0a06.zip
  .yarn/cache/clipanion-npm-4.0.0-rc.2-ad27d804c4-b0a9e11387.zip
  .yarn/cache/clone-response-npm-1.0.3-f71cb6aff5-06a2b61182.zip
  .yarn/cache/comment-json-npm-2.4.2-ad40caa02b-409aafaab6.zip
  .yarn/cache/decompress-response-npm-6.0.0-359de2878c-bd89d23141.zip
  .yarn/cache/defer-to-connect-npm-2.0.1-9005cc8c60-625ce28e1b.zip
  .yarn/cache/diff-npm-5.1.0-d24d222280-77a0d9beb9.zip
  .yarn/cache/dotenv-npm-16.3.1-e6d380a398-b95ff1bbe6.zip
  .yarn/cache/got-npm-11.8.6-89e7cd5d67-754dd44877.zip
  .yarn/cache/grapheme-splitter-npm-1.0.4-648f2bf509-108415fb07.zip
  .yarn/cache/http2-wrapper-npm-1.0.3-5b58ade1df-6a9b72a033.zip
  .yarn/cache/lowercase-keys-npm-2.0.0-1876065a32-f82a2b3568.zip
  .yarn/cache/mimic-response-npm-1.0.1-f6f85dde84-c5381a5eae.zip
  .yarn/cache/mimic-response-npm-3.1.0-a4a24b4e96-0d6f07ce6e.zip
  .yarn/cache/normalize-url-npm-6.1.0-b95bc12ece-95d948f9bd.zip
  .yarn/cache/p-cancelable-npm-2.1.1-9388305f02-8c6dc1f8dd.zip
  .yarn/cache/quick-lru-npm-5.1.1-e38e0edce3-a24cba5da8.zip
  .yarn/cache/resolve-alpn-npm-1.2.1-af77edd28b-b70b29c184.zip
  .yarn/cache/responselike-npm-2.0.1-7f64b6e122-360b6deb5f.zip
  .yarn/cache/tinylogic-npm-2.0.0-700fcc2fe0-c9417c4b65.zip
  .yarn/cache/treeify-npm-1.1.0-abf9292333-2f0dea9e89.zip
  .yarn/cache/tunnel-npm-0.0.6-b1c0830ea4-e27e7e896f.zip
  .yarn/cache/typanion-npm-3.14.0-8af344c436-8b03b19844.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/app/App.tsx
  packages/client/src/app/global.css
  packages/client/src/app/reset.css
  packages/client/src/shared/ui/styles/colors.ts
  packages/client/src/shared/ui/styles/index.ts
  packages/client/src/shared/ui/styles/theme.ts
  yarn.lock
Labels: 🎨 HTML&CSS, 🙋‍♂️ Question, FE

#123 [FE] Modal 컴포넌트 구현
  packages/client/src/app/App.tsx
  packages/client/src/shared/lib/types/theme.d.ts
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/shared/ui/styles/theme.ts
Labels: 🎨 HTML&CSS, 🐛 BugFix, 🙋‍♂️ Question, FE

#120 [FE] useFetch 커스텀 훅 구현
  .pnp.cjs
  .yarn/cache/axios-npm-1.6.2-2334cb6eee-9b77e030e8.zip
  .yarn/cache/follow-redirects-npm-1.15.3-ca69c47b72-915a2cf22e.zip
  .yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-fe7dd8b1bd.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/shared/hooks/index.ts
  packages/client/src/shared/hooks/useFetch.ts
  yarn.lock
Labels: ✨ Feature, FE

#124 [BE] POST /board/:id/image 요청 처리 구현 (게시글 이미지 파일 서버 로컬에 업로드)
  .pnp.cjs
  .yarn/cache/@types-multer-npm-1.4.11-a023fdbf13-ace8e9f5ac.zip
  .yarn/install-state.gz
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-image.dto.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/board/entities/image.entity.ts
  packages/server/test/board/board.e2e-spec.ts
  yarn.lock
Labels: ✨ Feature, ✅ Test, BE

#121 [FE] InputBar 컴포넌트 구현
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/inputBar/index.tsx
Labels: ✨ Feature, FE

#126 [FE] Button 컴포넌트 구현
  packages/client/src/shared/ui/button/button.tsx
  packages/client/src/shared/ui/button/index.tsx
  packages/client/src/shared/ui/styles/theme.ts
Labels: 🎨 HTML&CSS, 🐛 BugFix, FE

#125 [BE] SignIn시 RefreshToken 발급 및 Redis에 저장
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/user-constraints.decorator.ts
  packages/server/src/auth/dto/signin-user.dto.ts
  packages/server/src/auth/dto/signup-user.dto.ts
  packages/server/src/auth/enums/jwt.enum.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/config/jwt.config.ts
Labels: ✨ Feature, BE

#129 [BE] 커스텀 AuthGuard 작성
  .pnp.cjs
  .yarn/cache/@types-cookie-parser-npm-1.4.6-27287e1e43-56421a00d9.zip
  .yarn/cache/@types-passport-jwt-npm-3.0.13-55c5414e75-39aeafa92d.zip
  .yarn/cache/@types-passport-npm-1.0.16-7f245434f2-7120c1186c.zip
  .yarn/cache/@types-passport-strategy-npm-0.2.38-6460f7e728-d7d2b1782a.zip
  .yarn/cache/cookie-npm-0.4.1-cc5e2ebb42-4d7bc798df.zip
  .yarn/cache/cookie-parser-npm-1.4.6-a68f84d02a-9c2ade5459.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/cookie-auth.guard.ts
  packages/server/src/auth/redis.repository.ts
  packages/server/src/main.ts
  packages/server/src/utils/auth.util.ts
  yarn.lock
Labels: ✨ Feature, BE

#131 [BE] board 모듈 입력값 유효성 검증
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/dto/create-image.dto.ts
Labels: ✨ Feature, BE

#127 [FE] Search 컴포넌트 생성
  packages/client/src/shared/ui/search/Search.tsx
Labels: 🎨 HTML&CSS, FE

#130 [FE] Button 컴포넌트 추가 구현
  .pnp.cjs
  .yarn/cache/@babel-helper-string-parser-npm-7.23.4-b1f0d030c3-f348d5637a.zip
  .yarn/cache/@babel-types-npm-7.23.4-cd82933a3d-231954418e.zip
  .yarn/cache/@rollup-pluginutils-npm-5.0.5-cfa8fafc53-18a1f5a9af.zip
  .yarn/cache/@svgr-babel-plugin-add-jsx-attribute-npm-8.0.0-026be9c2be-a50bd0baa3.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-attribute-npm-8.0.0-c98774fd19-8a98e59bd9.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-empty-expression-npm-8.0.0-bee2c7d451-517dcca752.zip
  .yarn/cache/@svgr-babel-plugin-replace-jsx-attribute-value-npm-8.0.0-bf8ed25593-004bd18920.zip
  .yarn/cache/@svgr-babel-plugin-svg-dynamic-title-npm-8.0.0-c534fda2ad-80e0a7fcf9.zip
  .yarn/cache/@svgr-babel-plugin-svg-em-dimensions-npm-8.0.0-de7e3b5c02-73e92c8277.zip
  .yarn/cache/@svgr-babel-plugin-transform-react-native-svg-npm-8.1.0-9f7491cf96-655ed6bc7a.zip
  .yarn/cache/@svgr-babel-plugin-transform-svg-component-npm-8.0.0-2e9be9c6ad-4ac00bb99a.zip
  .yarn/cache/@svgr-babel-preset-npm-8.1.0-0dca9b0e1b-49367d3ad0.zip
  .yarn/cache/@svgr-core-npm-8.1.0-77cc138b8f-6a2f6b1bc7.zip
  .yarn/cache/@svgr-hast-util-to-babel-ast-npm-8.0.0-5d74d59e64-f4165b583b.zip
  .yarn/cache/@svgr-plugin-jsx-npm-8.1.0-e2710753df-07b4d9e00d.zip
  .yarn/cache/dot-case-npm-3.0.4-09675b5521-5b859ea650.zip
  .yarn/cache/entities-npm-4.5.0-7cdb83b832-5b039739f7.zip
  .yarn/cache/estree-walker-npm-2.0.2-dfab42f65c-53a6c54e20.zip
  .yarn/cache/lower-case-npm-2.0.2-151055f1c2-3d925e0903.zip
  .yarn/cache/no-case-npm-3.0.4-12884c3d98-8ef545f0b3.zip
  .yarn/cache/snake-case-npm-3.0.4-67f447c30d-ab19a91396.zip
  .yarn/cache/svg-parser-npm-2.0.4-1b0b6afbe9-02f6cb155d.zip
  .yarn/cache/vite-plugin-svgr-npm-4.2.0-e0c6a7a1f0-0a6400f209.zip
  .yarn/install-state.gz
  package.json
  packages/client/package.json
  packages/client/src/shared/ui/button/button.tsx
  packages/client/src/shared/ui/button/iconButton.tsx
  packages/client/src/shared/ui/button/index.ts
  packages/client/src/shared/ui/button/index.tsx
  packages/client/src/shared/ui/button/textButton.tsx
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/inputBar/index.tsx
  packages/client/src/shared/ui/modals/index.ts
  packages/client/src/widgets/loginModal/ui/index.ts
  packages/client/tsconfig.json
  packages/client/vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🐛 BugFix, FE

#135 [BE] SignOut시 토큰 제거
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/cookie-auth.guard.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/auth/redis.repository.ts
Labels: ✨ Feature, BE

#136 [BE] Board모듈 보안 : 게시글 본문 암복호화,Entity 관계적용, AuthGuard 적용, 게시글 생성 시 author 서버가 삽입
  .pnp.cjs
  .yarn/cache/crypto-npm-1.0.1-7cb8e3dca6-fcf7dbd68a.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/config/aes.config.ts
  packages/server/src/utils/aes.util.ts
  yarn.lock
Labels: ✨ Feature, 🐛 BugFix, BE

#137 [BE] user 외래키 활용하도록 메소드 개선, 좋아요 중복 비허용 (조인테이블 생성)
  packages/server/src/auth/decorators/get-user.decorator.ts
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/dto/user-data.dto.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/main.ts
  packages/server/src/utils/aes.util.ts
Labels: ✨ Feature, 🐛 BugFix, ⚡️ Enhancement, BE

#138 [BE] 깃헙 로그인 구현
  .pnp.cjs
  .yarn/cache/@types-uuid-npm-9.0.7-c380bb8654-b329ebd4f9.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/utils/auth.util.ts
  yarn.lock
Labels: ✨ Feature, BE

#134 [FE] Login 모달 구현
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/shared/ui/button/Button.tsx
  packages/client/src/shared/ui/button/IconButton.tsx
  packages/client/src/shared/ui/button/TextButton.tsx
  packages/client/src/shared/ui/button/button.tsx
  packages/client/src/shared/ui/button/generateButtonStyle.ts
  packages/client/src/shared/ui/button/index.ts
  packages/client/src/shared/ui/styles/theme.ts
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/landingScreen/lib/constants.ts
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/loginModal/ui/LeftButton.tsx
  packages/client/src/widgets/loginModal/ui/LoginContent.tsx
  packages/client/src/widgets/loginModal/ui/RightButton.tsx
  packages/client/src/widgets/loginModal/ui/TopButton.tsx
  packages/client/src/widgets/loginModal/ui/index.ts
  packages/client/src/widgets/logoAndStart/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#143 [FE] 로그인 및 랜딩 페이지
  packages/client/src/shared/store/userLoginStore.ts
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/landingScreen/lib/constants.ts
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/loginModal/ui/LoginContent.tsx
  packages/client/src/widgets/loginModal/ui/RightButton.tsx
  packages/client/src/widgets/logoAndStart/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#142 [FE] 글쓰기 모달, 카메라 이동
  .pnp.cjs
  .yarn/install-state.gz
  packages/client/index.html
  packages/client/src/entities/PostStars/index.tsx
  packages/client/src/entities/posts/index.ts
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/star/index.tsx
  packages/client/src/features/writingModal/index.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/hooks/index.ts
  packages/client/src/shared/hooks/useForwardRef.ts
  packages/client/src/shared/store/useWritingStore.ts
  packages/client/src/shared/ui/modals/ModalPortal.tsx
  packages/client/src/shared/ui/modals/index.ts
  packages/client/src/shared/ui/textArea/textArea.tsx
  packages/client/src/widgets/screen/index.tsx
  yarn.lock
Labels: ✨ Feature, FE

#144 [FE] Hotfix
  packages/client/src/shared/store/useCameraStore.ts
  packages/client/src/shared/store/useWritingStore.ts
  packages/client/src/shared/store/userLoginStore.ts
  packages/client/src/shared/ui/button/Button.tsx
  packages/client/src/shared/ui/button/iconButton.tsx
  packages/client/src/shared/ui/button/textButton.tsx
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/IconButton.tsx
  packages/client/src/shared/ui/buttons/TextButton.tsx
  packages/client/src/shared/ui/buttons/generateButtonStyle.ts
  packages/client/src/shared/ui/buttons/index.ts
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/widgets/loginModal/index.tsx
Labels: 🐛 BugFix, ♻️ Refactor, FE

#145 [BE] 이미지 NCP Object Storage에 업로드, 다운로드 (해결)
  .pnp.cjs
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  yarn.lock
Labels: ✨ Feature, 🐛 BugFix, BE

#139 [FE] 회원가입 모달
  .yarn/install-state.gz
  packages/client/src/app/global.css
  packages/client/src/shared/ui/buttons/button.tsx
  packages/client/src/shared/ui/buttons/iconButton.tsx
  packages/client/src/shared/ui/buttons/textButton.tsx
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/shared/ui/styles/theme.ts
  packages/client/src/shared/ui/toast/Toast.tsx
  packages/client/src/widgets/signupModal/ui/SignUpModal.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#140 [FE] 닉네임 설정 모달 구현
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
Labels: 🎨 HTML&CSS, FE

#146 [FE] Hotfix
  .yarn/install-state.gz
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/IconButton.tsx
  packages/client/src/shared/ui/buttons/TextButton.tsx
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/shared/ui/search/index.ts
  packages/client/src/shared/ui/textArea/textArea.tsx
  packages/client/src/shared/ui/toast/index.ts
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
Labels: ♻️ Refactor, FE

#147 [FE] 에셋 이동
  packages/client/src/assets/icon-add-24-white.svg
  packages/client/src/assets/icon-arrow-left-32-white.svg
  packages/client/src/assets/icon-arrow-right-17-white.svg
  packages/client/src/assets/icon-arrow-right-32-white.svg
  packages/client/src/assets/icon-back-32-white.svg
  packages/client/src/assets/icon-confirm-22.svg
  packages/client/src/assets/icon-eraser-24-active.svg
  packages/client/src/assets/icon-eraser-24-default.svg
  packages/client/src/assets/icon-naver-16-white.svg
  packages/client/src/assets/icon-pen-24-active.svg
  packages/client/src/assets/icon-pen-24-default.svg
  packages/client/src/assets/icon-photo-32-gray.svg
  packages/client/src/assets/icon-planetedit-24-white.svg
  packages/client/src/assets/icon-search-24-white.svg
  packages/client/src/assets/icon-shuffle-24-gray.svg
  packages/client/src/assets/icon-shuffle-24-white.svg
  packages/client/src/assets/icon-writte-24-white.svg
  packages/client/src/features/writingModal/index.tsx
  packages/client/src/shared/ui/textArea/index.ts
  packages/client/src/widgets/signupModal/SignUpModal.tsx
  packages/client/tsconfig.json
Labels: 🐛 BugFix, FE

#148 [FE] Svg 인식
  packages/client/src/app/App.tsx
Labels: 🐛 BugFix, FE

#150 [BE] GitHub Action을 이용한 자동 배포
  .github/workflows/deploy.yml
  docker-compose.yml
  nginx.conf
Labels: 🚀 Deploy, BE

#152 [BE] GitHub Action 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🚀 Deploy, 🐛 BugFix

#156 [Fix] Fix GitHub Actions Workflow Bug
  .github/workflows/cicd.yml
  .github/workflows/deploy.yml
Labels: 🐛 BugFix

#159 [Deploy] GitHub Actions를 통한 CI/CD 파이프라인 (수정수정수정수정)
  .github/workflows/cicd.yml
Labels: 🚀 Deploy, 🐛 BugFix

#160 [Deploy] GitHub Actions를 통한 CI/CD 파이프라인 (찐막)
  docker-compose.yml
Labels: 🚀 Deploy, BE

#158 [FE] 카메라 움직임
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/shared/lib/constants/api.ts
  packages/client/src/shared/lib/constants/camera.ts
  packages/client/src/shared/lib/constants/index.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/widgets/galaxy/index.tsx
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/landingScreen/lib/camera.ts
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/loginModal/ui/LeftButton.tsx
  packages/client/src/widgets/loginModal/ui/RightButton.tsx
  packages/client/src/widgets/loginModal/ui/TopButton.tsx
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, ⚡️ Enhancement, FE

#161 [FE] 회원가입 모달 UI 수정, validation 처리
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
  packages/client/src/widgets/signupModal/lib/constants.ts
  packages/client/src/widgets/signupModal/ui/CheckPwInputContainer.tsx
  packages/client/src/widgets/signupModal/ui/IdInputContainer.tsx
  packages/client/src/widgets/signupModal/ui/PwInputContainer.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#164 [BE] 네이버 로그인 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/utils/auth.util.ts
Labels: ✨ Feature, ♻️ Refactor, BE

#163 [FE] 모달창 자식요소 투명해지는 문제 해결
  packages/client/src/shared/ui/modals/Modal.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/shared/ui/styles/theme.ts
Labels: 🎨 HTML&CSS, 🐛 BugFix, FE

#165 [BE] 구글 로그인 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/utils/auth.util.ts
Labels: ✨ Feature, BE

#166 [FE] Axios Interceptor 추가
  packages/client/src/app/App.tsx
  packages/client/src/shared/apis/AxiosInterceptor.ts
  packages/client/src/shared/apis/index.ts
  packages/client/src/shared/apis/signUp.ts
Labels: ✨ Feature, FE

#167 [FE] 글 조회 모달 구현
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/postModal/PostModal.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/lib/types/post.ts
  packages/client/src/shared/store/usePostStore.ts
  packages/client/src/shared/store/useViewStore.ts
Labels: ✨ Feature, FE

#170 [BE] 글 생성 시 별 위치 및 스타일 정보 MongoDB에 저장
  .pnp.cjs
  .yarn/cache/@mongodb-js-saslprep-npm-1.1.1-73d5b62d41-b59fb1ed62.zip
  .yarn/cache/@nestjs-mongoose-npm-10.0.2-2d4bd943c4-1359081e34.zip
  .yarn/cache/@types-webidl-conversions-npm-7.0.3-dab9692d39-ac2ccff93b.zip
  .yarn/cache/@types-whatwg-url-npm-8.2.2-54c5c24e6c-7e5b6837da.zip
  .yarn/cache/bson-npm-6.2.0-3d364484ee-90f447dbaf.zip
  .yarn/cache/kareem-npm-2.5.1-79134fb43e-30c6b9a395.zip
  .yarn/cache/memory-pager-npm-1.5.0-46e20e6c81-2596e80c99.zip
  .yarn/cache/mongodb-connection-string-url-npm-2.6.0-af011ba17f-1e26b04506.zip
  .yarn/cache/mongodb-npm-6.2.0-e710a7f8df-aa806b7a01.zip
  .yarn/cache/mongoose-npm-8.0.1-d875460126-79332e2b69.zip
  .yarn/cache/mpath-npm-0.9.0-e79cc94aea-ac1a77ebbd.zip
  .yarn/cache/mquery-npm-5.0.0-e714f098ee-65b8a92d3b.zip
  .yarn/cache/sift-npm-16.0.1-ad548f4923-e3d1a68bab.zip
  .yarn/cache/sparse-bitfield-npm-3.0.3-cb80d0c89f-248c6ff7b5.zip
  .yarn/cache/tr46-npm-3.0.0-e1ae1ea7c9-cdc47cad3a.zip
  .yarn/cache/webidl-conversions-npm-7.0.0-e8c8e30c68-228d8cb6d2.zip
  .yarn/cache/whatwg-url-npm-11.0.0-073529d93a-f7ec264976.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/board/schemas/star.schema.ts
  packages/server/src/config/mongoose.config.ts
  yarn.lock
Labels: ✨ Feature, BE

#171 [FE] 하단바, 상단바 UI 구현
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Home/ui/UpperBar.tsx
  packages/client/src/pages/Home/ui/index.ts
  packages/client/src/pages/Home/ui/styled.ts
  packages/client/src/shared/lib/constants/index.ts
  packages/client/src/shared/lib/constants/width.ts
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/shared/ui/toast/Toast.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
Labels: 🎨 HTML&CSS, FE

#172 [FE] 라우팅 방식 설정
  packages/client/src/app/Router.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/index.tsx
Labels: ⚙ Setting, ♻️ Refactor, FE

#173 [FE] 은하 성능 최적화
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/shared/lib/constants/camera.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/styles/theme.ts
  packages/client/src/widgets/galaxy/Galaxy.tsx
  packages/client/src/widgets/galaxy/index.ts
  packages/client/src/widgets/galaxy/index.tsx
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/galaxy/lib/modules/index.ts
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/galaxy/lib/modules/positions.ts
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/loginModal/ui/RightButton.tsx
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐛 BugFix, ⚡️ Enhancement, FE

#175 [Deploy] 프론트 라우팅 문제 해결 (Nginx 설정 변경)
  nginx.conf
Labels: 🚀 Deploy

#177 [FE] 변경된 라우팅 설정 반영
  packages/client/index.html
  packages/client/src/app/Router.tsx
  packages/client/src/features/postModal/PostModal.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Landing/index.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/logoAndStart/index.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
Labels: ♻️ Refactor, FE

#180 [BE] Sharp 플랫폼 종속성 해결, GET /stars, GET /post/:id 프론트 요청에 맞게 새로 구현
  .pnp.cjs
  .yarn/install-state.gz
  Dockerfile-was
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/dto/user-data.dto.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/dto/get-post-by-id-res.dto.ts
  packages/server/src/star/dto/create-star.dto.ts
  packages/server/src/star/dto/get-star-res.dto.ts
  packages/server/src/star/dto/update-star.dto.ts
  packages/server/src/star/schemas/star.schema.ts
  packages/server/src/star/star.controller.ts
  packages/server/src/star/star.module.ts
  packages/server/src/star/star.service.ts
  packages/server/test/board/board.e2e-spec.ts
  packages/server/test/star/star.controller.spec.ts
  packages/server/test/star/star.service.spec.ts
  yarn.lock
Labels: ✨ Feature, 🐛 BugFix, BE

#178 [FE] UnderBar 컴포넌트 UI 변경
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
Labels: 🎨 HTML&CSS, FE

#182 [BE] Auth E2E 테스트 코드 수정
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/star/star.controller.ts
  packages/server/src/star/star.module.ts
  packages/server/src/star/star.service.ts
  packages/server/test/auth/auth.e2e-spec.ts
Labels: ✅ Test, BE

#183 [BE] GET /star, GET /post/:id 쿼리 최적화 (+ docker 컨테이너 재실행 설정)
  docker-compose.yml
  packages/server/src/board/board.service.ts
  packages/server/src/board/entities/image.entity.ts
  packages/server/src/config/typeorm.config.ts
  packages/server/src/star/star.service.ts
Labels: 🐛 BugFix, ⚡️ Enhancement, BE

#181 [FE] AlertDialog 컴포넌트 생성
  packages/client/src/shared/lib/constants/width.ts
  packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/modal/Modal.tsx
  packages/client/src/shared/ui/modal/ModalPortal.tsx
  packages/client/src/shared/ui/modal/index.ts
  packages/client/src/shared/ui/underBar/UnderBar.tsx
Labels: 🎨 HTML&CSS, FE

#188 [BE] 닉네임 검색 API 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/user.entity.ts
Labels: ✨ Feature, BE

#189 [BE] SignIn 에러 상태 코드 수정
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/dto/signin-user.dto.ts
  packages/server/src/auth/enums/user.enum.ts
Labels: ♻️ Refactor, BE

#190 [BE] PATCH & DELETE /post/:id 개선 및 트랜잭션 적용, PATCH /star/:id 구현
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/decorators/swagger/update-board-swagger.decorator.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/star/star.controller.ts
  packages/server/src/star/star.service.ts
Labels: ✨ Feature, ⚡️ Enhancement, BE

#185 [FE] 별 및 글에 대한 API 연동, 라우팅 설정, 로그아웃 구현
  .pnp.cjs
  .yarn/cache/@types-js-cookie-npm-3.0.6-c9126e5b48-173afaf5ea.zip
  .yarn/cache/js-cookie-npm-3.0.5-8fc8fcc9b4-04a0e56040.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/app/Router.tsx
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/postModal/PostModal.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/hooks/useFetch.ts
  packages/client/src/shared/lib/types/post.ts
  packages/client/src/shared/lib/types/star.ts
  packages/client/src/shared/store/usePostStore.ts
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/galaxy/Galaxy.tsx
  packages/client/src/widgets/loginModal/index.tsx
  yarn.lock
Labels: ⚙ Setting, ✨ Feature, 🎨 HTML&CSS, FE

#192 [FE] 글 삭제 기능 구현
  packages/client/src/features/postModal/PostModal.tsx
  packages/client/src/features/postModal/api/deletePost.ts
  packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
Labels: ✨ Feature, 📬 API, FE

#195 [BE] PATCH /post/:id 트랜잭션 개선, POST /post 트랜잭션 적용
  packages/server/src/board/board.service.ts
  packages/server/src/board/entities/image.entity.ts
Labels: ⚡️ Enhancement, BE

#198 [BE] LogInterceptor, TransactionInterceptor 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/cookie-auth.guard.ts
  packages/server/src/auth/decorators/get-user.decorator.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/interceptor/decorators/get-querry-runner.decorator.ts
  packages/server/src/interceptor/log.interceptor.ts
  packages/server/src/interceptor/transaction.interceptor.ts
  packages/server/src/star/star.controller.ts
  packages/server/src/util/aes.util.ts
  packages/server/src/util/auth.util.ts
  packages/server/src/util/interceptor.util.ts
Labels: ✨ Feature, BE

#199 [BE] Log 컬러 지정 및 catchError 추가
  packages/server/src/interceptor/log-color.code.ts
  packages/server/src/interceptor/log.interceptor.ts
  packages/server/src/interceptor/transaction.interceptor.ts
Labels: ♻️ Refactor, ⚡️ Enhancement, BE

#196 [FE] 글 작성 요청, 글 모달 스크롤바 구현
  packages/client/src/app/Router.tsx
  packages/client/src/features/postModal/index.ts
  packages/client/src/features/postModal/ui/ImageSlider.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/writingModal/api/sendPost.ts
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/shared/apis/AxiosInterceptor.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, 📬 API, FE

#204 [Deploy] sharp 플랫폼 에러 핫픽스
  .github/workflows/cicd.yml
Labels: 🚀 Deploy

#206 [Deploy] week4 배포
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile-was
Labels: 🚀 Deploy
