Repository boostcampwm2023/web16-B1G1, pull requests merged in 2023-12, with the labels that each got.

#208 [FE] 유저 로그인 확인, 스타일링 및 버그 수정, 로고와 파비콘 설정
  .yarn/install-state.gz
  packages/client/index.html
  packages/client/src/assets/favicon.png
  packages/client/src/assets/logo.png
  packages/client/src/features/postModal/api/deletePost.ts
  packages/client/src/features/postModal/ui/ImageSlider.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/hooks/index.ts
  packages/client/src/shared/hooks/useCheckLogin.ts
  packages/client/src/shared/store/index.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/shared/ui/textArea/TextArea.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/logoAndStart/index.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐛 BugFix, 📬 API, FE

#209 [FE] 글 제목 입력 기능, 몇가지 버그 수정
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/writingModal/api/sendPost.ts
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/textArea/TextArea.tsx
Labels: ✨ Feature, 🐛 BugFix, FE

#210 [FE] WarpScreen 수정
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/store/useLoadingStore.ts
  packages/client/src/shared/store/useScreenSwitchState.ts
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/lib/constants.ts
  packages/client/src/widgets/warpScreen/ui/BrightSphere.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: 🎨 HTML&CSS, ♻️ Refactor, FE

#213 [BE] 로그인한 사용자의 좋아요 여부 조회(GET /post/:id/is-liked)
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/decorators/swagger/get-is-liked-swagged.decorator.ts
Labels: ✨ Feature, BE

#216 [BE] docker 이미지 최적화
  Dockerfile-was
Labels: 🚀 Deploy, ⚡️ Enhancement

#217 [BE] 회원가입 시 은하 스타일 레코드 생성, 은하 스타일 조회 및 수정 API 구현
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/galaxy/dto/create-galaxy.dto.ts
  packages/server/src/galaxy/dto/update-galaxy.dto.ts
  packages/server/src/galaxy/galaxy.controller.ts
  packages/server/src/galaxy/galaxy.module.ts
  packages/server/src/galaxy/galaxy.service.ts
  packages/server/src/galaxy/schemas/galaxy.schema.ts
  packages/server/test/galaxy/galaxy.controller.spec.ts
  packages/server/test/galaxy/galaxy.service.spec.ts
Labels: ✨ Feature, BE

#215 [FE] 우주 검색 기능 구현
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/pages/Home/ui/UpperBar.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/apis/star.ts
  packages/client/src/shared/store/useOwnerStore.ts
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/loginModal/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 📬 API, FE

#214 [FE] 다른 사람 우주에서 UI 변경되게 처리
  packages/client/src/assets/icon-add-24-gray.svg
  packages/client/src/assets/icon-planetedit-24-gray.svg
  packages/client/src/assets/icon-writte-24-gray.svg
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Home/ui/UpperBar.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/apis/star.ts
  packages/client/src/shared/store/useOwnerStore.ts
  packages/client/src/shared/store/useScreenSwitchStore.ts
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: 🎨 HTML&CSS, FE

#218 [BE] OAuth Api 결과에 redirect 추가
  packages/server/src/auth/auth.controller.ts
Labels: ♻️ Refactor, BE

#221 [Deploy] nginx.conf에 client-max-body-size 옵션 추가
  nginx.conf
Labels: 🚀 Deploy, BE

#222 [FE] OAuth 로그인, 회원가입 / 은하 커스텀
  packages/client/src/app/Router.tsx
  packages/client/src/assets/logo/Github.png
  packages/client/src/assets/logo/Google.png
  packages/client/src/assets/logo/Naver.png
  packages/client/src/shared/apis/signUp.ts
  packages/client/src/shared/store/index.ts
  packages/client/src/shared/store/useCustomStore.ts
  packages/client/src/shared/store/useGalaxyStore.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/slider/Slider.tsx
  packages/client/src/shared/ui/slider/index.ts
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/galaxy/Galaxy.tsx
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/galaxy/lib/modules/positions.ts
  packages/client/src/widgets/galaxyCustom/index.tsx
  packages/client/src/widgets/galaxyCustom/ui/RightButton.tsx
  packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
  packages/client/src/widgets/galaxyCustom/ui/Sliders.tsx
  packages/client/src/widgets/galaxyCustom/ui/index.ts
  packages/client/src/widgets/loginModal/lib/constants.ts
  packages/client/src/widgets/loginModal/lib/index.ts
  packages/client/src/widgets/loginModal/ui/LoginContent.tsx
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#225 [FE] 닉네임 모달, 좋아요 버그 수정
  packages/client/src/entities/like/Like.tsx
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
Labels: 🐛 BugFix, FE

#227 [FE] hofix 반영
  packages/client/src/entities/like/Like.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
Labels: 🚀 Deploy, FE

#229 [BE] 백엔드에서 admin 모듈 생성
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.module.ts
  packages/server/src/admin/admin.service.ts
  packages/server/src/app.module.ts
Labels: ✨ Feature, BE

#230 [FE] Leva 설정, 우주 배경색 변경
  packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
  packages/client/src/widgets/landingScreen/index.tsx
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#231 [FE] 별 라벨 디자인 변경
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/star/index.tsx
Labels: 🎨 HTML&CSS, FE

#233 [BE] Exception Filter 구현 및 check-signin api 수정
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/swagger/get-username-by-sharelink.decorator.ts
  packages/server/src/exception-filter/http.exception-filter.ts
  packages/server/src/main.ts
Labels: ✨ Feature, BE

#232 [BE] admin 배포용 Dockerfile-Web 수정, cicd 수정
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile-web
  nginx.conf
  packages/admin/.gitignore
  packages/admin/index.html
  packages/admin/src/App.tsx
  packages/admin/src/components/Nav.tsx
Labels: 🚀 Deploy

#234 [BE] shared ui (버튼, 표) 구현, board(전체 글 조회)
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.23.5-6e68b78aa3-ca679cc91b.zip
  .yarn/cache/@emotion-babel-plugin-npm-11.11.0-c1dcc4c884-89cbb6ec0e.zip
  .yarn/cache/@emotion-cache-npm-11.11.0-3e6e449071-a23ab5ab2f.zip
  .yarn/cache/@emotion-hash-npm-0.9.1-650576c2b1-cdafe5da63.zip
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.1-794afe6a94-7c2aabdf0c.zip
  .yarn/cache/@emotion-memoize-npm-0.8.1-9b1e35ff15-dffed372fc.zip
  .yarn/cache/@emotion-react-npm-11.11.1-a07d6a6ebd-1aea4d735b.zip
  .yarn/cache/@emotion-serialize-npm-1.1.2-4b856d3761-d243e0e5ab.zip
  .yarn/cache/@emotion-sheet-npm-1.2.2-a918ac483c-69827a1bfa.zip
  .yarn/cache/@emotion-styled-npm-11.11.0-9a95c8527d-a168bd7a8a.zip
  .yarn/cache/@emotion-unitless-npm-0.8.1-bcf0a8f565-a1ed508628.zip
  .yarn/cache/@emotion-use-insertion-effect-with-fallbacks-npm-1.0.1-730758c66c-a15b216794.zip
  .yarn/cache/@emotion-utils-npm-1.2.1-3d04f99348-db43ca8033.zip
  .yarn/cache/@emotion-weak-memoize-npm-0.3.1-bfc18213af-ed514b3cb9.zip
  .yarn/cache/@types-parse-json-npm-4.0.2-f87f65692e-b1b863ac34.zip
  .yarn/cache/babel-plugin-macros-npm-3.1.0-320e781f4e-c6dfb15de9.zip
  .yarn/cache/convert-source-map-npm-1.9.0-e294555f4b-281da55454.zip
  .yarn/cache/cosmiconfig-npm-7.1.0-13a5090bcd-b923ff6af5.zip
  .yarn/cache/find-root-npm-1.1.0-a16a94005f-1abc7f3bf2.zip
  .yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-fe0889169e.zip
  .yarn/cache/source-map-npm-0.5.7-7c3f035429-904e767bb9.zip
  .yarn/cache/stylis-npm-4.2.0-6b07f11c99-a7128ad5a8.zip
  .yarn/cache/yaml-npm-1.10.2-0e780aebdf-5c28b9eb7a.zip
  .yarn/install-state.gz
  packages/admin/.env.development
  packages/admin/.env.production
  packages/admin/package.json
  packages/admin/src/App.tsx
  packages/admin/src/components/Board/Board.tsx
  packages/admin/src/components/Nav.tsx
  packages/admin/src/components/shared/Button.tsx
  packages/admin/src/components/shared/Table.tsx
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.service.ts
  yarn.lock
Labels: ✨ Feature, 🎨 HTML&CSS, BE

#238 [FE] 닉네임 받는 시점 변경
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/loginModal/index.tsx
Labels: 🐛 BugFix, FE

#235 [FE] 카메라 최대거리 설정, 은하 커스텀 추가기능
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/lib/constants/camera.ts
  packages/client/src/shared/store/useCameraStore.ts
  packages/client/src/shared/ui/underBar/UnderBar.tsx
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/galaxyCustom/index.tsx
  packages/client/src/widgets/galaxyCustom/ui/LeftButton.tsx
  packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
  packages/client/src/widgets/galaxyCustom/ui/Sliders.tsx
  packages/client/src/widgets/galaxyCustom/ui/TopButton.tsx
  packages/client/src/widgets/galaxyCustom/ui/index.ts
  packages/client/src/widgets/loginModal/index.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#237 [FE] 글 수정 기능 구현
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/postModal/ui/ImageSlider.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/shared/ui/textArea/TextArea.tsx
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#236 [BE] sharelink, search api 수정
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/swagger/get-share-link-swagger.decorator.ts
  packages/server/src/auth/decorators/swagger/get-username-by-sharelink.decorator.ts
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/auth/pipes/StatusValidationPipe.ts
Labels: ♻️ Refactor, BE

#240 [BE] 어드민용 시스템 정보 조회 API, 페이지 컴포넌트 구현
  .gitignore
  .pnp.cjs
  .yarn/cache/os-utils-npm-0.0.14-139244a17c-58fb91364b.zip
  .yarn/install-state.gz
  packages/admin/src/App.tsx
  packages/admin/src/components/SystemInfo/SystemInfo.tsx
  packages/server/package.json
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.service.ts
  yarn.lock
Labels: ✨ Feature, 🎨 HTML&CSS, BE

#242 [BE] 어드민 페이지 디스크 사용량 조회, 게시글 상세 조회
  packages/admin/src/components/Board/Board.tsx
  packages/admin/src/components/SystemInfo/SystemInfo.tsx
  packages/admin/src/components/shared/Button.tsx
  packages/server/src/admin/admin.service.ts
Labels: ✨ Feature, 🎨 HTML&CSS, BE

#243 [BE] GET /star API 인터페이스 수정, 어드민 기능 리팩토링
  packages/admin/src/components/Board/Board.tsx
  packages/admin/src/components/SystemInfo/SystemInfo.tsx
  packages/server/src/admin/admin.service.ts
  packages/server/src/star/star.service.ts
Labels: ✨ Feature, ♻️ Refactor, BE

#246 [BE] OAuth2.0 통한 회원가입 시 Galaxy Record 생성
  packages/server/src/auth/auth.service.ts
Labels: 🐛 BugFix, BE

#245 [FE] 은하 커스텀 화면
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/apis/galaxy.ts
  packages/client/src/shared/apis/index.ts
  packages/client/src/shared/store/useCustomStore.ts
  packages/client/src/shared/store/useGalaxyStore.ts
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/galaxy/lib/modules/positions.ts
  packages/client/src/widgets/galaxyCustom/index.tsx
  packages/client/src/widgets/galaxyCustom/ui/LeftButton.tsx
  packages/client/src/widgets/galaxyCustom/ui/Sliders.tsx
  packages/client/src/widgets/galaxyCustom/ui/TopButton.tsx
Labels: 🐛 BugFix, FE

#249 [FE] HotFix
  packages/client/src/widgets/signupModal/ui/IdInputContainer.tsx
Labels: 🐛 BugFix, FE

#250 [BE] Hotfix
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
Labels: 🐛 BugFix

#252 [FE] 예외사항 처리, 닉네임 처리 방식 변경
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Home/ui/UpperBar.tsx
  packages/client/src/shared/ui/underBar/UnderBar.tsx
Labels: 🐛 BugFix, FE

#253 [FE] zustand get 사용
  packages/client/src/pages/Home/index.tsx
  packages/client/src/shared/apis/galaxy.ts
  packages/client/src/shared/store/useCustomStore.ts
  packages/client/src/shared/store/useGalaxyStore.ts
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/LeftButton.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/TopButton.tsx
Labels: ⚡️ Enhancement, FE

#256 [FE] Build fix
  packages/client/src/pages/Home/index.tsx
Labels: 🚀 Deploy, 🐛 BugFix, FE

#258 [Deploy] Week5 Ver4 배포
  packages/client/src/pages/Home/index.tsx
Labels: 🚀 Deploy

#259 [FE] 별 생성 api 수정
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
Labels: 🐛 BugFix, 📬 API, FE

#260 [FE] Hotfix
  packages/client/src/shared/apis/login.ts
  packages/client/src/widgets/loginModal/index.tsx
Labels: 🐛 BugFix, FE

#261 [FE] 값 조절, 데이터 리페칭 구현
  packages/client/src/entities/posts/apis/getMyPost.ts
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/star/lib/constants/index.ts
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/screen/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 📬 API, FE

#263 [FE] 카메라 광원
  packages/client/src/widgets/screen/index.tsx
  packages/client/src/widgets/screen/ui/CameraLight.tsx
  packages/client/src/widgets/screen/ui/index.ts
Labels: ✨ Feature, FE

#262 [FE] 공유하기 모달 구현
  packages/client/src/app/Router.tsx
  packages/client/src/assets/icon-check-purple.svg
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/backgroundStars/BackgroundStars.tsx
  packages/client/src/features/star/Star.tsx
  packages/client/src/features/writingModal/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Home/ui/index.ts
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/pages/Landing/ui/styled.ts
  packages/client/src/shared/apis/share.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/shared/ui/inputBar/index.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustom.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/logoAndStart/LogoAndStart.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/shareModal/ShareModal.tsx
  packages/client/src/widgets/shareModal/lib/types.ts
  packages/client/src/widgets/shareModal/ui/LinkContainer.tsx
  packages/client/src/widgets/shareModal/ui/SearchSetContainer.tsx
  packages/client/src/widgets/starCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 📬 API, 🥰 Accessibility, FE

#264 [FE] Hotfix
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustom.tsx
Labels: 🐛 BugFix, FE

#265 Fe develop
  packages/client/src/app/Router.tsx
  packages/client/src/assets/icon-check-purple.svg
  packages/client/src/entities/posts/apis/getMyPost.ts
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/backgroundStars/BackgroundStars.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/star/Star.tsx
  packages/client/src/features/star/lib/constants/index.ts
  packages/client/src/features/writingModal/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Home/ui/index.ts
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/pages/Landing/ui/styled.ts
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/apis/share.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/shared/ui/inputBar/index.tsx
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustom.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/logoAndStart/LogoAndStart.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/screen/ui/CameraLight.tsx
  packages/client/src/widgets/screen/ui/index.ts
  packages/client/src/widgets/shareModal/ShareModal.tsx
  packages/client/src/widgets/shareModal/lib/types.ts
  packages/client/src/widgets/shareModal/ui/LinkContainer.tsx
  packages/client/src/widgets/shareModal/ui/SearchSetContainer.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/starCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: 🚀 Deploy, FE

#267 [BE] board 모듈 리팩토링, star & galaxy 모듈 e2e 테스트 작성 및 테스트
  packages/admin/src/components/shared/Table.tsx
  packages/server/src/admin/admin.module.ts
  packages/server/src/admin/admin.service.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/galaxy/galaxy.controller.ts
  packages/server/src/galaxy/galaxy.module.ts
  packages/server/src/galaxy/galaxy.service.ts
  packages/server/src/star/star.service.ts
  packages/server/test/galaxy/galaxy.e2e-spec.ts
  packages/server/test/star/star.e2e-spec.ts
Labels: ♻️ Refactor, ✅ Test, BE

#268 [BE] ExceptionStatistics 컴포넌트 Filter 컴포넌트 구현
  packages/admin/src/App.tsx
  packages/admin/src/components/ExceptionStatistics/Chart/Chart.tsx
  packages/admin/src/components/ExceptionStatistics/ExceptionStatistics.tsx
  packages/admin/src/components/ExceptionStatistics/Filter/Filter.tsx
  packages/admin/src/components/ExceptionStatistics/exception.interface.ts
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.service.ts
Labels: ✨ Feature, BE

#271 [BE] 감정 분석 API 구현
  packages/server/src/app.module.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/config/clova.config.ts
  packages/server/src/sentiment/dto/get-sentiment.dto.ts
  packages/server/src/sentiment/sentiment.controller.ts
  packages/server/src/sentiment/sentiment.module.ts
  packages/server/src/sentiment/sentiment.service.ts
  packages/server/test/sentiment/sentiment.controller.spec.ts
  packages/server/test/sentiment/sentiment.service.spec.ts
Labels: ✨ Feature, BE

#270 [FE] 시작 페이지 기본은하 적용, 화면 전환 페이드 아웃 적용, 검색창 엔터키 사용 가능하게 변경
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/star/Star.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/store/useGalaxyStore.ts
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustom.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/warpScreen/lib/constants.ts
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: ⚡️ Enhancement, FE

#273 [BE] sentiment, board 모듈 e2e 테스트 코드 작성, 테스트, 코드 개선
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/entities/board.entity.ts
  packages/server/src/sentiment/sentiment.service.ts
  packages/server/test/board/board.e2e-spec.ts
  packages/server/test/sentiment/sentiment.e2e-spec.ts
Labels: 🐛 BugFix, ✅ Test, BE

#272 [FE] 여러가지 작은 기능들 구현
  .pnp.cjs
  .yarn/cache/@types-howler-npm-2.2.11-dd9e5eb3f8-0a6b6d3585.zip
  .yarn/cache/@types-react-howler-npm-5.2.3-e13418b6ae-8c5ddded67.zip
  .yarn/cache/fscreen-npm-1.2.0-cbeb194fbc-1a5cb44446.zip
  .yarn/cache/howler-npm-2.2.4-689ccf19b1-74a295f56f.zip
  .yarn/cache/react-full-screen-npm-1.1.1-4d2e312e1b-02c6034c6a.zip
  .yarn/cache/react-howler-npm-5.2.0-211ee607c8-b4b4572851.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/assets/bgm.mp3
  packages/client/src/features/audio/Audio.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/store/useAudioStore.ts
  packages/client/src/widgets/nickNameSetModal/lib/constants.ts
  packages/client/src/widgets/nickNameSetModal/ui/NickNameInputContainer.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#275 [BE] Auth 모듈 에러 메세지 영어로 수정
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/cookie-auth.guard.ts
  packages/server/src/auth/decorators/get-user.decorator.ts
  packages/server/src/auth/decorators/swagger/sign-in-swagger.decorator.ts
  packages/server/src/auth/dto/signin-user.dto.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/auth/pipes/StatusValidationPipe.ts
  packages/server/src/util/auth.util.ts
Labels: ♻️ Refactor, BE

#276 [BE] 에러 메시지 포맷 통일
  packages/server/src/board/board.service.ts
  packages/server/src/galaxy/galaxy.service.ts
  packages/server/src/sentiment/sentiment.service.ts
  packages/server/src/star/star.service.ts
Labels: ♻️ Refactor, BE

#277 [BE] board 트랜잭션 제어 방식 변경, 파일 관련 메소드 서비스로 분리
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/file.service.ts
Labels: ♻️ Refactor, BE

#278 [BE] galaxy, sentiment 서비스 유닛 테스트
  packages/server/test/galaxy/galaxy.service.spec.ts
  packages/server/test/sentiment/sentiment.service.spec.ts
Labels: ✅ Test, BE

#280 [Deploy] week5 금요일 배포
  packages/client/src/assets/bgm.mp3
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/lib/constants/camera.ts
  packages/client/src/widgets/galaxy/Galaxy.tsx
  packages/client/src/widgets/loginModal/ui/LoginContent.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/starCustomModal/lib/constants.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/cookie-auth.guard.ts
  packages/server/src/auth/decorators/get-user.decorator.ts
  packages/server/src/auth/decorators/swagger/sign-in-swagger.decorator.ts
  packages/server/src/auth/dto/signin-user.dto.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/auth/pipes/StatusValidationPipe.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/board/board.module.ts
  packages/server/src/board/board.service.ts
  packages/server/src/board/file.service.ts
  packages/server/src/galaxy/galaxy.service.ts
  packages/server/src/sentiment/sentiment.service.ts
  packages/server/src/star/star.service.ts
  packages/server/src/util/auth.util.ts
  packages/server/test/galaxy/galaxy.service.spec.ts
  packages/server/test/sentiment/sentiment.service.spec.ts
Labels: 🚀 Deploy

#283 [FE] 검색한 사용자, 링크로 접근한 사용자 라우터 분리
  packages/client/src/app/Router.tsx
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/apis/login.ts
  packages/client/src/shared/apis/share.ts
  packages/client/src/shared/hooks/index.ts
  packages/client/src/shared/hooks/useCheckLogin.ts
  packages/client/src/shared/hooks/useCheckNickName.ts
  packages/client/src/shared/routes/PrivateRoute.tsx
  packages/client/src/shared/routes/PublicRoute.tsx
  packages/client/src/shared/store/index.ts
  packages/client/src/shared/store/useErrorStore.ts
  packages/client/src/shared/store/useOwnerStore.ts
  packages/client/src/shared/store/useScreenSwitchStore.ts
  packages/client/src/shared/ui/alert/Alert.tsx
  packages/client/src/shared/ui/alert/index.ts
  packages/client/src/shared/ui/alertDialog/index.ts
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/signupModal/SignUpModal.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/server/src/board/board.controller.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 📬 API, ♻️ Refactor, FE

#284 [FE] 다른 사람 은하에서 별 클릭했을 때 home으로 돌아가는 에러 해결
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
Labels: 🐛 BugFix, FE

#285 [FE] 하단바 디자인 수정
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/shared/lib/constants/width.ts
  packages/client/src/shared/routes/PrivateRoute.tsx
  packages/client/src/shared/routes/PublicRoute.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
Labels: 🎨 HTML&CSS, 🐛 BugFix, FE

#286 [BE] Board, Star 유닛 테스트 구현, Board e2e 테스트 개선(이미지 첨부)
  packages/server/src/board/board.service.ts
  packages/server/src/star/star.service.ts
  packages/server/test/board/board.e2e-spec.ts
  packages/server/test/board/board.service.spec.ts
  packages/server/test/board/dto/get-board-by-id-res.dto.spec.ts
  packages/server/test/board/sample-image.ts
  packages/server/test/star/dto/get-star-res.dto.spec.ts
  packages/server/test/star/star.service.spec.ts
Labels: ♻️ Refactor, ✅ Test, BE

#289 [FE] 글쓰기 모달 이미지 크기 수정
  packages/client/src/app/Router.tsx
  packages/client/src/features/writingModal/index.ts
  packages/client/src/features/writingModal/ui/Images.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
Labels: 🎨 HTML&CSS, FE

#290 [FE] 버튼 연속 클릭 방지 기능 구현
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/RightButton.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/starCustomModal/ui/SentimentButton.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: ✨ Feature, 📬 API, FE

#291 [FE] 마참내 폰트 적용
  packages/client/src/app/global.css
  packages/client/src/assets/fonts/Pretendard-Bold.otf
  packages/client/src/assets/fonts/Pretendard-Bold.woff
  packages/client/src/assets/fonts/Pretendard-Bold.woff2
  packages/client/src/assets/fonts/Pretendard-Medium.otf
  packages/client/src/assets/fonts/Pretendard-Medium.woff
  packages/client/src/assets/fonts/Pretendard-Medium.woff2
Labels: 🎨 HTML&CSS, FE

#287 [FE] 배경음악 버튼, 별 겹침 및 라우팅 버그 수정
  packages/client/src/app/App.tsx
  packages/client/src/app/Router.tsx
  packages/client/src/entities/posts/apis/getMyPost.ts
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/writingModal/index.ts
  packages/client/src/features/writingModal/ui/Images.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/hooks/useRefresh.ts
  packages/client/src/shared/lib/types/view.ts
  packages/client/src/shared/store/useAudioStore.ts
  packages/client/src/shared/store/useViewStore.ts
  packages/client/src/shared/ui/audioButton/AudioButton.tsx
  packages/client/src/shared/ui/search/Search.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/RightButton.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/shareModal/ShareModal.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/starCustomModal/apis/getSentimentColor.ts
  packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts
  packages/client/src/widgets/starCustomModal/ui/SentimentButton.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: ✨ Feature, 🐛 BugFix, FE

#292 [FE] 버그 수정
  packages/client/src/app/App.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
  packages/client/src/widgets/starCustomModal/apis/getSentimentColor.ts
Labels: 🐛 BugFix, FE

#295 [FE] 코치마커 추가
  .pnp.cjs
  .yarn/cache/@gilbarbara-deep-equal-npm-0.1.2-98a7c259d1-ef441034a3.zip
  .yarn/cache/@gilbarbara-deep-equal-npm-0.3.1-59e6185977-009584aa91.zip
  .yarn/cache/@gilbarbara-helpers-npm-0.9.0-3aabeaa261-07457da54e.zip
  .yarn/cache/@gilbarbara-types-npm-0.2.2-40872223ec-c998bfb41f.zip
  .yarn/cache/deep-diff-npm-1.0.2-ab33725091-cc3e315ba9.zip
  .yarn/cache/is-lite-npm-0.8.2-e09c91529d-ed4b99d47f.zip
  .yarn/cache/is-lite-npm-1.2.0-304a5ffe73-3bde0175c5.zip
  .yarn/cache/leva-npm-0.9.35-da054c7dd9-9555db5e0b.zip
  .yarn/cache/popper.js-npm-1.16.1-a99192bd83-1c1a826f75.zip
  .yarn/cache/react-floater-npm-0.7.9-c1546b4d7f-3fa58e968a.zip
  .yarn/cache/react-innertext-npm-1.1.5-50613b71c6-45335918ac.zip
  .yarn/cache/react-joyride-npm-2.7.1-78984ee8a0-4aefbe8a6a.zip
  .yarn/cache/scroll-npm-3.0.1-26a443f234-5b0c98089b.zip
  .yarn/cache/scrollparent-npm-2.1.0-2ce4ab214f-b377ec5a46.zip
  .yarn/cache/tree-changes-npm-0.11.2-eb720d8e1c-bcdcf9b550.zip
  .yarn/cache/tree-changes-npm-0.9.3-e337138b32-e7a38ed3c2.zip
  .yarn/cache/type-fest-npm-4.8.3-5f50002256-978edf5d00.zip
  .yarn/install-state.gz
  packages/client/package.json
  packages/client/src/app/global.css
  packages/client/src/features/coachMarker/CoachMarker.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#293 [BE] Auth Controller 유닛 테스트 작성, checkNickname Api 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/swagger/check-nickname-swagger.decorator.ts
  packages/server/test/auth/auth.controller.spec.ts
  packages/server/test/auth/auth.e2e-spec.ts
Labels: ✅ Test, BE

#296 [BE] 어드민 페이지 계정인증 구현
  packages/admin/src/App.tsx
  packages/admin/src/components/Board/Board.tsx
  packages/admin/src/components/ExceptionStatistics/ExceptionStatistics.tsx
  packages/admin/src/components/Login/Login.tsx
  packages/admin/src/components/SystemInfo/SystemInfo.tsx
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.module.ts
  packages/server/src/admin/admin.service.ts
  packages/server/src/admin/jwt.strategy.ts
Labels: ✨ Feature, BE

#297 [BE] User Status값 NEW 추가
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/auth/enums/user.enum.ts
Labels: ✨ Feature, BE

#299 [BE] be-develop 병합
  packages/admin/src/App.tsx
  packages/admin/src/components/Board/Board.tsx
  packages/admin/src/components/ExceptionStatistics/ExceptionStatistics.tsx
  packages/admin/src/components/Login/Login.tsx
  packages/admin/src/components/SystemInfo/SystemInfo.tsx
  packages/server/src/admin/admin.controller.ts
  packages/server/src/admin/admin.module.ts
  packages/server/src/admin/admin.service.ts
  packages/server/src/admin/jwt.strategy.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/swagger/check-nickname-swagger.decorator.ts
  packages/server/src/auth/entities/share-link.entity.ts
  packages/server/src/auth/entities/user.entity.ts
  packages/server/src/auth/enums/user.enum.ts
  packages/server/src/board/board.service.ts
  packages/server/src/star/star.service.ts
  packages/server/test/auth/auth.controller.spec.ts
  packages/server/test/auth/auth.e2e-spec.ts
  packages/server/test/board/board.e2e-spec.ts
  packages/server/test/board/board.service.spec.ts
  packages/server/test/board/dto/get-board-by-id-res.dto.spec.ts
  packages/server/test/board/sample-image.ts
  packages/server/test/star/dto/get-star-res.dto.spec.ts
  packages/server/test/star/star.service.spec.ts
Labels: 🚀 Deploy, BE

#294 [FE] 자잘한 작업
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/postModal/ui/ImageSlider.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/hooks/useCheckNickName.ts
  packages/client/src/shared/store/index.ts
  packages/client/src/shared/store/useOwnerStore.ts
  packages/client/src/shared/store/useScreenSwitchStore.ts
  packages/client/src/shared/ui/alert/Alert.tsx
  packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
  packages/client/src/shared/ui/alertDialog/index.ts
  packages/client/src/shared/ui/audioButton/AudioButton.tsx
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/index.ts
  packages/client/src/shared/ui/toast/Toast.tsx
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/galaxy/lib/modules/positions.ts
  packages/client/src/widgets/galaxyCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/shareModal/ui/LinkContainer.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: ✨ Feature, 🐛 BugFix, ⚡️ Enhancement, FE

#298 [FE] 404 페이지, 코치마크 버튼 구현, 은하 커스텀 모달 알럿창 및 토스트 구현
  packages/client/src/app/Router.tsx
  packages/client/src/assets/logos/404.png
  packages/client/src/features/coachMarker/CoachButton.tsx
  packages/client/src/features/coachMarker/CoachMarker.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/hooks/useCheckNickName.ts
  packages/client/src/shared/ui/textArea/TextArea.tsx
  packages/client/src/widgets/error/FallBackComponent.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#300 [FE] 은하 색상 변경
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/features/writingModal/ui/Images.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/shared/lib/constants/camera.ts
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/loginModal/ui/TopButton.tsx
  packages/client/src/widgets/shareModal/ui/LinkContainer.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐛 BugFix, FE

#301 [HotFix] 사진 업로드 개수 제한 변경
  packages/server/src/board/board.controller.ts
Labels: 🐛 BugFix, BE

#302 [FE] Fix bug
  packages/client/src/shared/ui/alert/Alert.tsx
  packages/client/src/widgets/loginModal/ui/TopButton.tsx
  packages/client/src/widgets/screen/Screen.tsx
Labels: 🐛 BugFix, FE

#303 [BE] be-develop 병합
  packages/server/src/board/board.controller.ts
Labels: 🚀 Deploy, BE

#305 [HotFix] checksum 매치 오류를 해결하기 위해 yarn install 전 캐시 지우기
  .github/workflows/deploy.yml
Labels: 🚀 Deploy, 🐛 BugFix

#307 [Deploy] Week6 Ver1 배포 (yarn에러 해결시도)
  .github/workflows/cicd.yml
Labels: 🚀 Deploy, 🐛 BugFix

#309 리드미 작성
  README.md
Labels: 📝 Docs

#313 [BE] 외부 API를 요청하는 엔드포인트 Rate Limiting
  .pnp.cjs
  .yarn/cache/@nestjs-throttler-npm-5.1.0-12d7d9629c-8dc900ca1d.zip
  .yarn/cache/charenc-npm-0.0.2-aca0c2f207-a45ec39363.zip
  .yarn/cache/crypt-npm-0.0.2-033627d94f-adbf263441.zip
  .yarn/cache/is-buffer-npm-1.1.6-08199d9ccc-ae18aa0b6e.zip
  .yarn/cache/md5-npm-2.3.0-86c49d3915-14a21d597d.zip
  .yarn/install-state.gz
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/board/board.controller.ts
  packages/server/src/sentiment/sentiment.controller.ts
  yarn.lock
Labels: ⚡️ Enhancement, BE

#310 [FE] WarpScreen과 FadeoutScreen 통합
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: ♻️ Refactor, FE

#311 [FE] 버그 수정, 일부 기능 숨기기
  packages/client/src/shared/hooks/useCheckNickName.ts
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: 🐛 BugFix, ⚡️ Enhancement, FE

#308 [FE] 최적화
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/controls/Controls.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/star/Star.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/shared/hooks/useCheckNickName.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/IconButton.tsx
  packages/client/src/shared/ui/buttons/TextButton.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/screen/ui/LevaTheme.ts
  packages/client/src/widgets/screen/ui/index.ts
  packages/client/src/widgets/shareModal/ui/LinkContainer.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: 🐛 BugFix, ⚡️ Enhancement, FE

#312 [FE] 버그 수정, 디자인 변경, 좋아요 알럿창 구현
  packages/client/src/entities/like/Like.tsx
  packages/client/src/features/postModal/ui/PostModal.tsx
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/shared/apis/search.ts
  packages/client/src/shared/ui/alert/Alert.tsx
  packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
  packages/client/src/shared/ui/modal/Modal.tsx
  packages/client/src/shared/ui/textArea/TextArea.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/starCustomModal/ui/SentimentButton.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐛 BugFix, FE

#314 [FE] 모달 문제 해결
  packages/client/src/shared/ui/modal/Modal.tsx
  packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
  packages/client/src/widgets/loginModal/LoginModal.tsx
  packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
  packages/client/src/widgets/underBar/UnderBar.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
Labels: 🐛 BugFix, FE

#316 [FE] Galaxy, WarpScreen 색상 변경
  packages/client/src/widgets/galaxy/lib/constants/index.ts
  packages/client/src/widgets/warpScreen/lib/constants.ts
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: 🎨 HTML&CSS, FE

#319 [FE] 버튼 새로고침 문제 해결, warp 개선
  packages/client/src/app/global.css
  packages/client/src/features/postModal/ui/ImageSlider.tsx
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/IconButton.tsx
  packages/client/src/shared/ui/buttons/TextButton.tsx
Labels: 🐛 BugFix, ⚡️ Enhancement, FE

#320 [FE] 전체화면 오류 수정, 감정 분석 에러 처리, 구글 애널리틱스
  packages/client/index.html
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/lib/constants/error.ts
Labels: ✨ Feature, 🐛 BugFix, FE

#317 [BE] trust proxy 설정 (원본 ip 반환하여 throttler 문제 해결)
  packages/server/src/app.module.ts
  packages/server/src/main.ts
Labels: 🐛 BugFix, BE

#322 [FE] 페이지네이션 버그 해결
  packages/client/src/features/postModal/ui/ImageSlider.tsx
Labels: 🐛 BugFix, FE

#323 [FE] 뒤로가기 오류 해결
  packages/client/src/pages/Home/Home.tsx
Labels: 🐛 BugFix, FE

#324 [FE] 버튼 에러 수정
  packages/client/src/widgets/shareModal/ShareModal.tsx
Labels: 🐛 BugFix, FE

#326 [BE] check-nickname API 리턴값 변경
  packages/server/src/auth/auth.service.ts
Labels: 🐛 BugFix, BE

#327 [BE] check-signin api 유저 status값 리턴하도록 수정 HotFix
  packages/server/src/auth/auth.service.ts
Labels: 🐛 BugFix, BE

#328 [BE] Search Api 유저 status private이 아니면 나오도록 수정
  packages/server/src/auth/auth.service.ts
Labels: 🐛 BugFix, BE

#330 [BE] be-develop 병합
  packages/server/src/auth/auth.service.ts
Labels: 🚀 Deploy, BE

#329 [FE] 비공개 은하 검색 버그 수정
  packages/client/index.html
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/shared/apis/search.ts
  packages/client/src/shared/lib/constants/error.ts
  packages/client/src/shared/routes/ModalRoot.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: 🐛 BugFix, FE

#331 [FE] 버그 해결
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts
Labels: 🐛 BugFix, ⚡️ Enhancement, FE

#332 리드미 작성
  README.md
  packages/client/index.html
  packages/client/src/features/writingModal/ui/WritingModal.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/shared/apis/search.ts
  packages/client/src/shared/lib/constants/error.ts
  packages/client/src/shared/routes/ModalRoot.tsx
  packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts
  packages/client/src/widgets/upperBar/UpperBar.tsx
Labels: 📝 Docs

#335 리드미 작성
  README.md
Labels: 📝 Docs

#337 리드미 작성
  README.md
Labels: 📝 Docs

#334 [FE] Theme 사용
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/coachMarker/CoachButton.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/ui/inputBar/InputBar.tsx
  packages/client/src/shared/ui/textArea/TextArea.tsx
Labels: ♻️ Refactor, FE

#336 [FE] 별 생성 위치 조정, 별 생성 삭제 애니메이션
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/entities/posts/ui/Posts.tsx
  packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts
Labels: ✨ Feature, 🐛 BugFix, FE

#341 [FE] 이미지 버그 수정, assets 폴더 정리
  packages/client/src/assets/favicon.png
  packages/client/src/assets/icon-add-24-gray.svg
  packages/client/src/assets/icon-add-24-white.svg
  packages/client/src/assets/icon-arrow-left-32-white.svg
  packages/client/src/assets/icon-arrow-right-17-white.svg
  packages/client/src/assets/icon-arrow-right-32-white.svg
  packages/client/src/assets/icon-back-32-white.svg
  packages/client/src/assets/icon-check-purple.svg
  packages/client/src/assets/icon-confirm-22.svg
  packages/client/src/assets/icon-eraser-24-active.svg
  packages/client/src/assets/icon-eraser-24-default.svg
  packages/client/src/assets/icon-naver-16-white.svg
  packages/client/src/assets/icon-pen-24-active.svg
  packages/client/src/assets/icon-pen-24-default.svg
  packages/client/src/assets/icon-photo-32-gray.svg
  packages/client/src/assets/icon-planetedit-24-gray.svg
  packages/client/src/assets/icon-planetedit-24-white.svg
  packages/client/src/assets/icon-search-24-white.svg
  packages/client/src/assets/icon-shuffle-24-gray.svg
  packages/client/src/assets/icon-shuffle-24-white.svg
  packages/client/src/assets/icon-writte-24-gray.svg
  packages/client/src/assets/icon-writte-24-white.svg
  packages/client/src/assets/logo.png
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/logoAndStart/LogoAndStart.tsx
  packages/client/src/widgets/writingModal/ui/Images.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
  packages/client/tsconfig.json
Labels: 🐛 BugFix, ♻️ Refactor, FE

#340 [FE] 타입 사용, 오류 해결, 폰트 적용
  packages/client/src/app/global.css
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/lib/types/button.ts
  packages/client/src/shared/lib/types/index.ts
  packages/client/src/shared/lib/types/star.ts
  packages/client/src/shared/lib/types/warp.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/generateButtonStyle.ts
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: 🐛 BugFix, FE

#342 [FE] 코치마크에 전체화면 설명 추가
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/coachMarker/CoachMarker.tsx
  packages/client/src/shared/apis/core/AxiosInterceptor.ts
  packages/client/src/shared/styles/theme.ts
  packages/client/src/widgets/error/FallBackComponent.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/shareModal/ui/SearchSetContainer.tsx
  packages/client/src/widgets/starCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/upperBar/ui/GoBackButton.tsx
  packages/client/src/widgets/upperBar/ui/SearchBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/vite.config.ts
Labels: 🎨 HTML&CSS, ♻️ Refactor, FE

#343 [FE] 12/14 배포
  packages/client/src/app/global.css
  packages/client/src/assets/favicon.png
  packages/client/src/assets/icon-add-24-gray.svg
  packages/client/src/assets/icon-add-24-white.svg
  packages/client/src/assets/icon-arrow-left-32-white.svg
  packages/client/src/assets/icon-arrow-right-17-white.svg
  packages/client/src/assets/icon-arrow-right-32-white.svg
  packages/client/src/assets/icon-back-32-white.svg
  packages/client/src/assets/icon-check-purple.svg
  packages/client/src/assets/icon-confirm-22.svg
  packages/client/src/assets/icon-eraser-24-active.svg
  packages/client/src/assets/icon-eraser-24-default.svg
  packages/client/src/assets/icon-naver-16-white.svg
  packages/client/src/assets/icon-pen-24-active.svg
  packages/client/src/assets/icon-pen-24-default.svg
  packages/client/src/assets/icon-photo-32-gray.svg
  packages/client/src/assets/icon-planetedit-24-gray.svg
  packages/client/src/assets/icon-planetedit-24-white.svg
  packages/client/src/assets/icon-search-24-white.svg
  packages/client/src/assets/icon-shuffle-24-gray.svg
  packages/client/src/assets/icon-shuffle-24-white.svg
  packages/client/src/assets/icon-writte-24-gray.svg
  packages/client/src/assets/icon-writte-24-white.svg
  packages/client/src/assets/logo.png
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/coachMarker/CoachMarker.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/apis/core/AxiosInterceptor.ts
  packages/client/src/shared/lib/types/button.ts
  packages/client/src/shared/lib/types/index.ts
  packages/client/src/shared/lib/types/star.ts
  packages/client/src/shared/lib/types/warp.ts
  packages/client/src/shared/styles/theme.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/generateButtonStyle.ts
  packages/client/src/widgets/error/FallBackComponent.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/logoAndStart/LogoAndStart.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/shareModal/ui/SearchSetContainer.tsx
  packages/client/src/widgets/starCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/upperBar/ui/GoBackButton.tsx
  packages/client/src/widgets/upperBar/ui/SearchBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
  packages/client/src/widgets/writingModal/ui/Images.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
  packages/client/tsconfig.json
  packages/client/vite.config.ts
Labels: 🚀 Deploy, FE

#344 12/14 배포
  README.md
  packages/client/src/app/global.css
  packages/client/src/assets/favicon.png
  packages/client/src/assets/icon-add-24-gray.svg
  packages/client/src/assets/icon-add-24-white.svg
  packages/client/src/assets/icon-arrow-left-32-white.svg
  packages/client/src/assets/icon-arrow-right-17-white.svg
  packages/client/src/assets/icon-arrow-right-32-white.svg
  packages/client/src/assets/icon-back-32-white.svg
  packages/client/src/assets/icon-check-purple.svg
  packages/client/src/assets/icon-confirm-22.svg
  packages/client/src/assets/icon-eraser-24-active.svg
  packages/client/src/assets/icon-eraser-24-default.svg
  packages/client/src/assets/icon-naver-16-white.svg
  packages/client/src/assets/icon-pen-24-active.svg
  packages/client/src/assets/icon-pen-24-default.svg
  packages/client/src/assets/icon-photo-32-gray.svg
  packages/client/src/assets/icon-planetedit-24-gray.svg
  packages/client/src/assets/icon-planetedit-24-white.svg
  packages/client/src/assets/icon-search-24-white.svg
  packages/client/src/assets/icon-shuffle-24-gray.svg
  packages/client/src/assets/icon-shuffle-24-white.svg
  packages/client/src/assets/icon-writte-24-gray.svg
  packages/client/src/assets/icon-writte-24-white.svg
  packages/client/src/assets/logo.png
  packages/client/src/entities/posts/ui/Post.tsx
  packages/client/src/features/coachMarker/CoachMarker.tsx
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/apis/core/AxiosInterceptor.ts
  packages/client/src/shared/lib/types/button.ts
  packages/client/src/shared/lib/types/index.ts
  packages/client/src/shared/lib/types/star.ts
  packages/client/src/shared/lib/types/warp.ts
  packages/client/src/shared/styles/theme.ts
  packages/client/src/shared/ui/buttons/Button.tsx
  packages/client/src/shared/ui/buttons/generateButtonStyle.ts
  packages/client/src/widgets/error/FallBackComponent.tsx
  packages/client/src/widgets/galaxyCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/landingScreen/LandingScreen.tsx
  packages/client/src/widgets/loginModal/ui/OauthLogin.tsx
  packages/client/src/widgets/logoAndStart/LogoAndStart.tsx
  packages/client/src/widgets/screen/Screen.tsx
  packages/client/src/widgets/shareModal/ui/SearchSetContainer.tsx
  packages/client/src/widgets/starCustomModal/ui/SampleScreen.tsx
  packages/client/src/widgets/upperBar/UpperBar.tsx
  packages/client/src/widgets/upperBar/ui/GoBackButton.tsx
  packages/client/src/widgets/upperBar/ui/SearchBar.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
  packages/client/src/widgets/writingModal/ui/Images.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
  packages/client/tsconfig.json
  packages/client/vite.config.ts
Labels: 🚀 Deploy

#345 [FE] 빌드 에러 수정
  packages/client/src/widgets/writingModal/ui/Images.tsx
Labels: 🚀 Deploy, 🐛 BugFix, FE

#347 12/14 배포
  packages/client/src/widgets/writingModal/ui/Images.tsx
Labels: 🚀 Deploy

#348 [FE] 파비콘. 린트 fix
  packages/client/index.html
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
Labels: 🐛 BugFix, FE

#351 [BE] 리팩토링, 에러 처리 개선
  packages/server/src/admin/admin.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/file.service.ts
  packages/server/src/interceptor/transaction.interceptor.ts
  packages/server/src/star/dto/update-star.dto.ts
Labels: ♻️ Refactor, ⚡️ Enhancement, BE

#353 [FE] 배경별 Distance limit
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
Labels: 🐛 BugFix, FE

#354 12/14 마지막 배포
  README.md
  packages/client/src/widgets/galaxy/lib/modules/instances.tsx
  packages/server/src/admin/admin.service.ts
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/board/file.service.ts
  packages/server/src/interceptor/transaction.interceptor.ts
  packages/server/src/star/dto/update-star.dto.ts
Labels: 🚀 Deploy

#355 리드미 작성
  README.md
Labels: 📝 Docs

#356 [FE] WarpScreen FadeoutScreen에 onAnimationEnd 추가
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
Labels: ♻️ Refactor, FE

#357 [FE] 글 수정 제목 및 본문 제한
  packages/client/src/shared/lib/types/post.ts
  packages/client/src/widgets/postModal/ui/PostModal.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
Labels: ✨ Feature, FE

#358 [HotFix] 로깅 문제 해결, 게시글 maxlength 문제 해결
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/exception-filter/http.exception-filter.ts
  packages/server/src/interceptor/log.interceptor.ts
Labels: 🐛 BugFix, BE

#360 [FE] v1.0.0 배포
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/lib/types/post.ts
  packages/client/src/widgets/postModal/ui/PostModal.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
Labels: 🚀 Deploy, FE

#361 [Deploy] Ver1.0.0 릴리즈
  README.md
  packages/client/src/pages/Home/Home.tsx
  packages/client/src/shared/lib/types/post.ts
  packages/client/src/widgets/postModal/ui/PostModal.tsx
  packages/client/src/widgets/warpScreen/WarpScreen.tsx
  packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
  packages/client/src/widgets/writingModal/ui/WritingModal.tsx
  packages/server/src/board/dto/create-board.dto.ts
  packages/server/src/exception-filter/http.exception-filter.ts
  packages/server/src/interceptor/log.interceptor.ts
Labels: 🚀 Deploy
